# Generated by Django 4.2.23 on 2025-06-30 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='content',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
