# Generated by Django 4.2.23 on 2025-07-26 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0004_tag_movie_image_alter_comment_movie_movie_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='movies', to='movie.tag'),
        ),
    ]
