# Generated by Django 4.2.23 on 2025-07-26 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0006_alter_movie_tags'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='tags',
            new_name='tag',
        ),
    ]
