# Generated by Django 4.2.23 on 2025-07-26 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0009_alter_comment_writer'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='click_num',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
